fix tolerations types to always be string
stolostron/backplane-operator pull request #286
Opened 2022-08-29 15:52 UTC by eemurphy

Signed-off-by: Erin Murphy <erinmurp@redhat.com>

issue: https://github.com/stolostron/backlog/issues/24856

2022-08-29 16:22 UTC, JakobGray requested changes

2022-08-29 16:22 UTC, JakobGray commented on pkg/rendering/renderer.go
> +		fmt.Println(reflect.Indirect(v).Field(i).Interface())
All the print statements used for debugging should come out

2022-08-29 16:22 UTC, JakobGray commented on pkg/rendering/renderer.go
> +	vals, _ := chartutil.ReadValues(inrec)
The errors here should not be ignored

2022-08-30 14:42 UTC, ray-harris commented
Is there any reason we're defining our own Toleration struct instead of using the k8s defined toleration struct?

https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3021-L3046

2022-08-30 15:05 UTC, eemurphy commented
@ray-harris I may be incorrect, but we can not use the MarshalJSON() method with a type not defined inside the current package. I get this error if I try: `invalid receiver type "k8s.io/api/core/v1".Toleration (type not defined in this package)` 

I inherited some of this code from Jakob, and he made that change to just make our own version of Toleration so we could use the marshal method. I couldn't find any work around, though looking now maybe we could have just wrapped the k8s Toleration struct inside our own struct, which isn't too different from the change here

2022-08-30 17:13 UTC, JakobGray commented
The reason the toleration struct was in my code was so I could play around with marshaling options without updating all the chart templates, because they're defined in the templates as `{{ if .Key }} key: {{ .Key }} {{- end }}` so the modification my struct had was to add that capitalization (`json:"Key"`)

2022-08-31 13:33 UTC, ray-harris commented
/lgtm

2022-08-31 13:38 UTC, merged