2940 hosted proxy
stolostron/backplane-operator pull request #414
Opened 2023-03-27 20:47 UTC by cameronmwall

Issue: https://issues.redhat.com/browse/ACM-2940

2023-03-27 20:47 UTC, cameronmwall commented
/hold

2023-03-28 18:12 UTC, JakobGray requested changes
(comment from https://github.com/stolostron/backplane-operator/pull/390) Can you provide a list of commands to run to verify everything is deployed as it should be? For example:
```
oc get deploy cluster-manager-webhook-konnectivity-agent -n <mceNS>
oc get service cluster-manager-work-webhook -n <mceNS>
KUBECONFIG=<hosted-kubeconfig> oc get service .....
```

I tried the oc api-resources call and nothing stood out to me before or after the changes were applied so I'm not sure if anything happened.

I tried running this code and the hosted MCE couldn't get off the ground because of this error.
```
2023-03-28T18:00:40Z	INFO	error rendering chart: konnectivity-cm-webhook-agent
2023-03-28T18:00:40Z	INFO	template: konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml:70:25: executing "konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml" at <.Values.global.imageOverrides.apiserver_network_policy>: map has no entry for key "apiserver_network_policy"
2023-03-28T18:00:40Z	INFO	template: konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml:70:25: executing "konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml" at <.Values.global.imageOverrides.apiserver_network_policy>: map has no entry for key "apiserver_network_policy"	{"controller": "multiclusterengine", "controllerGroup": "multicluster.openshift.io", "controllerKind": "MultiClusterEngine", "MultiClusterEngine": {"name":"wombo"}, "namespace": "", "name": "wombo", "reconcileID": "8bc31536-bf60-44c2-9d68-16b6974ef36d"}
```
After you've made your changes please test them in a running environment before requesting another code review.

2023-03-30 20:43 UTC, cameronmwall commented
> (comment from #390) Can you provide a list of commands to run to verify everything is deployed as it should be? For example:
> 
> ```
> oc get deploy cluster-manager-webhook-konnectivity-agent -n <mceNS>
> oc get service cluster-manager-work-webhook -n <mceNS>
> KUBECONFIG=<hosted-kubeconfig> oc get service .....
> ```
> 
> I tried the oc api-resources call and nothing stood out to me before or after the changes were applied so I'm not sure if anything happened.
> 
> I tried running this code and the hosted MCE couldn't get off the ground because of this error.
> 
> ```
> 2023-03-28T18:00:40Z	INFO	error rendering chart: konnectivity-cm-webhook-agent
> 2023-03-28T18:00:40Z	INFO	template: konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml:70:25: executing "konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml" at <.Values.global.imageOverrides.apiserver_network_policy>: map has no entry for key "apiserver_network_policy"
> 2023-03-28T18:00:40Z	INFO	template: konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml:70:25: executing "konnectivity-cm-webhook-agent/templates/cm-webhook-agent.yaml" at <.Values.global.imageOverrides.apiserver_network_policy>: map has no entry for key "apiserver_network_policy"	{"controller": "multiclusterengine", "controllerGroup": "multicluster.openshift.io", "controllerKind": "MultiClusterEngine", "MultiClusterEngine": {"name":"wombo"}, "namespace": "", "name": "wombo", "reconcileID": "8bc31536-bf60-44c2-9d68-16b6974ef36d"}
> ```
> 
> After you've made your changes please test them in a running environment before requesting another code review.

```
oc get mce
oc get deployment -n <hosted cluster manager namespace>
oc get service -n <hosted target namespace>
oc get deployment-n <hosted target namespace>
oc get networkpolicy konnectivity-server-from-hub-ns -n <hosted cluster namespace>
```

We can check that the MCE has come up to available. In the hosted cluster manager namespace, we can check that the registration and work web hook deployments are up and running. In the hosted target namespace we can look for the services. Then, we can check to make sure that the cluster IPs from the services in the hosted target namespace match the konnectivity server deployment in the hosted target namespace

2023-03-30 20:44 UTC, cameronmwall commented on controllers/hosted.go
> +	addresses := []string{registrationWebhookService.Spec.ClusterIP, workWebhookService.Spec.ClusterIP}
From my testing, there is no risk of panicking. If the services are not found, the reconciler simply moves on and uses the default values for IP

2023-03-31 18:48 UTC, JakobGray commented
> We can check that the MCE has come up to available. In the hosted cluster manager namespace, we can check that the registration and work web hook deployments are up and running. In the hosted target namespace we can look for the services. Then, we can check to make sure that the cluster IPs from the services in the hosted target namespace match the konnectivity server deployment in the hosted target namespace

@cameronmwall When you say hosted target namespace do you mean the MCE targetNS on the hosting cluster, or a namespace on the hosted cluster?

2023-03-31 18:51 UTC, JakobGray reviewed
I think everything is now getting deployed. As a sanity test I tried the webhook and got an error. Is this a valid way to test the webhook proxying?

```
KUBECONFIG=${HOSTED_CLUSTER_KUBECONFIG}.kubeconfig oc apply -f work-example.yaml
Error from server (InternalError): error when creating "work-example.yaml": Internal error occurred: failed calling webhook "manifestworkvalidators.admission.work.open-cluster-management.io": failed to call webhook: Post "https://cluster-manager-work-webhook.wombo-cluster-manager.svc:443/validate-work-open-cluster-management-io-v1-manifestwork?timeout=10s": EOF
```

2023-05-04 13:12 UTC, closed without merging